### ISSUE TITLE
Code 3 feedback

### ISSUE THREAD

**Issue by bigfatnoob** [tarunchhabra26/fss16dst#3]
- Birthday Paradox: The probability should be around 50%. 
- Poker: How is probability more than 1? Moreover flush has the highest probability which seems wrong. Do check on the definitions and your code.

**Comment by dndesai** [comment]
Poker: The probability is not 1, It was  printing error in final output , instead of printing its occurrence once in the number of times it printed 'has probability'. The mypoker.py file has been updated. for eg for flush it says : 'flush happens one time in 33.08'

**Comment by tarunchhabra26** [comment]
The output for the birthday paradox problem was for sample size 50. If the sample size is around 23 then the probability comes down to 50%. Have made changes to the code to display sample size also. As per @dndesai the poker issue is also resolved. Hence closing this. Thanks !
